FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port that your Next.js app runs on
EXPOSE 3000

# Command to run your Next.js application in development mode
CMD ["npm", "run", "dev"]