import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import { Toaster } from 'sonner'
import Header from './components/header'
import './globals.css'
import { ClerkProvider } from './providers/clerk-provider'
import { ThemeProvider } from './providers/theme-provider'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn('min-h-screen font-sans antialiased', fontSans.variable)}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          disableTransitionOnChange
        >
          <ClerkProvider>
            <Header />
            <main className='container'>
              <div className='mt-10'>{children}</div>
            </main>
          </ClerkProvider>
        </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
  )
}
